Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/_compat.py", line 72, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 198, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/_compat.py", line 72, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 198, in _read_from_socket
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    data = recv(self._sock, socket_read_size)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/_compat.py", line 72, in recv
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4019, in execute
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return execute(conn, stack, raise_on_error)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3894, in _execute_transaction
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
if not block and not conn.can_read(timeout=timeout):    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4019, in execute
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return execute(conn, stack, raise_on_error)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3894, in _execute_transaction

  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3894, in _execute_transaction
    self.parse_response(connection, '_')
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 222, in _read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
    self.parse_response(connection, '_')
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    response = self._parser.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 222, in _read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 230, in can_read
    self._read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 201, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    self.parse_response(connection, '_')
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 324, in read_response
    raw = self._buffer.readline()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 256, in readline
    self._read_from_socket()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 222, in _read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    connection.connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
        sock = self._connect()sock = self._connect()

  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
        raise errraise err

  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
        sock.connect(socket_address)sock.connect(socket_address)

ConnectionRefusedErrorConnectionRefusedError: : [Errno 111] Connection refused[Errno 111] Connection refused


During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,return _run_code(code, main_globals, None,

  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
        exec(code, run_globals)exec(code, run_globals)

  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
        main()main()

  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
        click.Group(commands=commands)(prog_name="bench")click.Group(commands=commands)(prog_name="bench")

  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)return self.main(*args, **kwargs)

  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)rv = self.invoke(ctx)

  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4012, in execute
    conn = self.connection_pool.get_connection('MULTI',
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 427, in read_from_socket
    bufflen = recv_into(self._sock, self._buffer)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/_compat.py", line 75, in recv_into
    return sock.recv_into(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 427, in read_from_socket
    bufflen = recv_into(self._sock, self._buffer)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/_compat.py", line 75, in recv_into
    return sock.recv_into(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3894, in _execute_transaction
    self.parse_response(connection, '_')
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3977, in parse_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4019, in execute
    result = Redis.parse_response(
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 452, in read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
    return execute(conn, stack, raise_on_error)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3894, in _execute_transaction
    self.parse_response(connection, '_')
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 452, in read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)    
raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionErrorredis.exceptions: .Connection closed by server.ConnectionError
: Connection closed by server.
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Exception in thread Thread-1Thread-1:
:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 627, in work
    self.unsubscribe()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 532, in unsubscribe
    self.pubsub.unsubscribe()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3600, in unsubscribe
    return self.execute_command('UNSUBSCRIBE', *args)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3466, in execute_command
    self.connection = self.connection_pool.get_connection(
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
Exception in thread Thread-1:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,Traceback (most recent call last):

  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    self.run()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3718, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3617, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3503, in parse_response
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    exec(code, run_globals)    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    if not block and not conn.can_read(timeout=timeout):
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 734, in can_read
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    return self._parser.can_read(timeout)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 416, in can_read
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return self.read_from_socket(timeout=timeout,
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3894, in _execute_transaction
    self.parse_response(connection, '_')
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response

  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 110, in <module>
    main()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/commands/scheduler.py", line 203, in start_worker
    start_worker(queue, quiet=quiet)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 196, in start_worker
    Worker(queues, name=get_worker_name(queue)).work(logging_level=logging_level)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 626, in work
    self.register_death()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/rq/worker.py", line 326, in register_death
    p.execute()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 4019, in execute
    return execute(conn, stack, raise_on_error)
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3894, in _execute_transaction
    self.parse_response(connection, '_')
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 3977, in parse_response
    result = Redis.parse_response(
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
    response = self._parser.read_response()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 470, in read_response
    self.read_from_socket()
  File "/home/euge0604/Desktop/str_modifier/frappe-bench/env/lib/python3.8/site-packages/redis/connection.py", line 429, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
